server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

s3:
  packages:
    name: "alpha-archipelago-packages"


dynamodb:
  versionsets:
    name: "versionsets.alpha"
    revisions:
      name: "versionsets.revisions.alpha"


aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4OERLSQXOW"
    key: "uGN1m4pb+cjoXdVLzn9mVL5VLLdlNeXvuyZVVGHY"

endpoints:
  package-service: "http://localhost:8080"