server:
  port: 8081
  error:
    include-stacktrace: never

logging:
  level:
    org.springframework.cloud: 'DEBUG'
    com.hulu: 'ERROR'
    com.hulu.mdp: 'INFO'
    com.hulu.mdp.kaper.test: 'DEBUG'
  pattern:
    console: '%d{HH:mm:ss.SSS}[%-5level][%X{RequestId}][%c{1}]: %msg%n'
    file: "%d %p %c{1.} [%t] %m%n"
  file: 'build/logs/app-%d{yyyy-MM-dd-HH}.log'

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

s3:
  packages:
    name: "alpha-archipelago-packages"

dynamodb:
  versionsets:
    name: "versionsets.alpha"
  versionsets.latest:
    name: "versionsets.latest.alpha"
  versionsets.revisions:
    name: "versionsets.revisions.alpha"


aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4OERLSQXOW"
    key: "uGN1m4pb+cjoXdVLzn9mVL5VLLdlNeXvuyZVVGHY"